### ISSUE TITLE
[edit] Add resource when not logged on triggers logon dialog but logging on redirects to user page

### ISSUE THREAD

**Issue by ddeboer** [ddeboer/ginger#65]
In gitlab by @fred on Nov 17, 2015, 11:01

This logon_required works without redirect on http://www.reinwardtcommunity.nl but 
redirects on http://orkestindeklas.dev

the javascript in _logon_box.tpl
```
z_transport("controller_logon", "ubf", { msg: "logon_redirect", page: '{{ page|default:q.p|escapejs }}' }); ```
is triggered in http://orkestindeklas.dev
but not in http://www.reinwardtcommunity.nl

the buttons are on query pages

**Comment by ddeboer** [comment]
In gitlab by @fred on Nov 17, 2015, 11:26

Title changed from **[edit] Add resource when logged on triggers logon dialog but logging on redirects to user page** to **[edit] Add resource when not logged on triggers logon dialog but logging on redirects to user page**

**Comment by ddeboer** [comment]
In gitlab by @david on Nov 19, 2015, 08:39

mentioned in merge request !6

**Comment by ddeboer** [comment]
In gitlab by @fred on Nov 19, 2015, 15:40

mentioned in commit fe298a0ce3330e07d472769afcc5a9047526b06f

**Comment by fred** [comment]
guys, i belienve this is not "@fred" you are looking for 😄

**Comment by ddeboer** [comment]
Whoops sorry, trying to automate some import from GitLab to GitHub. 😓
